### ISSUE TITLE
Add PUT function to profile-page endpoint

### ISSUE THREAD

**Issue by hasandemirkiran** [bounswe/bounswe2020group9#187] opened 2020-12-04 21:38 UTC
Please add PUT feature to profile-page calls

**Comment by ocebenzer** [comment] 2020-12-05 08:45
The server is out-of-date, updating it

**Comment by ocebenzer** [comment] 2020-12-06 18:48
it should be working now

**Comment by ocebenzer** [comment] 2020-12-21 15:08
As far as I know, the problem is solved. closing the issue.

**Closed by ocebenzer** 2020-12-21 15:08 UTC
Labels: Backend, Status - Needs review
