### ISSUE TITLE
Favorites section for main page

### ISSUE THREAD

**Issue by alcanunsal** [bounswe/bounswe2020group9#80] opened 2020-05-27 01:04 UTC
I have tried a few things but I believe the light section from bootstrap css cannot be divided, or at least I wasn't able to divide it for Favorites section. However, maybe we can implement a sidebar like in the link below:

https://www.w3schools.com/w3css/w3css_sidebar.asp

Looking forward for your thoughts..

**Comment by ocebenzer** [comment] 2020-05-27 07:39
Working on it

**Comment by hasandemirkiran** [comment] 2020-05-27 08:17
Already check yesterday keep looking today.

**Comment by ocebenzer** [comment] 2020-05-27 08:23
I think I managed to add a sidebar as suggested:
when you click button "favorites" favorites section opens
when you click once again, favorites section closes

The problem is that favorites section is at the very bottom, instead of being on left, @hasandemirkiran can you relocate the div?

**Comment by ocebenzer** [comment] 2020-05-27 08:26
Pushing my last version to Frontend_Development_AstronomicalPictureOfTheDay

**Comment by alcanunsal** [comment] 2020-05-27 11:01
@ocebenzer I think your version seems good, however "add to favorites" functionality seems to not working. :( Dou you have any idea why that might be?

**Comment by ocebenzer** [comment] 2020-05-27 11:21
if you mean the error: 
**Uncaught TypeError: Cannot read property 'firstChild' of null**
if favorites sidebar is closed, the add button can't find the sidebar
However, the POST request to the server is received and if favorites sidebar gets opened you can view it.
seems like a minor bug, it can be fixed easily

**Comment by alcanunsal** [comment] 2020-05-27 12:01
@ocebenzer , thank you for your efforts. As I see, favorites section in Frontend_Development branch is working without any errors.

**Comment by hasandemirkiran** [comment] 2020-05-27 12:09
I have updated the Favorites part and seems nicely working. Closing the issue.

**Closed by hasandemirkiran** 2020-05-27 12:09 UTC
